kPBX_rootObject = 'rootObject'
kPBX_objects = 'objects'
kPBX_archiveVersion = 'archiveVersion'
kPBX_objectVersion = 'objectVersion'
kPBX_classes = 'classes'

kPBX_ProjectRef = 'ProjectRef'

kPBX_isa = 'isa'

kPBX_TARGET_name = 'name'
kPBX_TARGET_productName = 'productName'
kPBX_TARGET_buildConfigurationList = 'buildConfigurationList'
kPBX_TARGET_buildPhases = 'buildPhases'
kPBX_TARGET_dependencies = 'dependencies'
kPBX_TARGET_productReference = 'productReference'
kPBX_TARGET_buildSettings = 'buildSettings'
kPBX_TARGET_productInstallPath = 'productInstallPath'
kPBX_TARGET_productSettingsXML = 'productSettingsXML'
kPBX_TARGET_shouldUseHeadermap = 'shouldUseHeadermap'
kPBX_TARGET_buildRules = 'buildRules'
kPBX_TARGET_passBuildSettingsInEnvironment = 'passBuildSettingsInEnvironment'
kPBX_TARGET_buildArgumentsString = 'buildArgumentsString'
kPBX_TARGET_buildToolPath = 'buildToolPath'
kPBX_TARGET_buildWorkingDirectory = 'buildWorkingDirectory'
kPBX_TARGET_settingsToExpand = 'settingsToExpand'
kPBX_TARGET_settingsToPassInEnvironment = 'settingsToPassInEnvironment'
kPBX_TARGET_settingsToPassOnCommandLine = 'settingsToPassOnCommandLine'
kPBX_TARGET_productType = 'productType'
kPBX_TARGET_buildProperties = 'buildProperties'

kPBX_PHASE_buildActionMask = 'buildActionMask'
kPBX_PHASE_files = 'files'
kPBX_PHASE_runOnlyForDeploymentPostprocessing = 'runOnlyForDeploymentPostprocessing'
kPBX_PHASE_contextName = 'contextName'
kPBX_PHASE_isSharedContext = 'isSharedContext'
kPBX_PHASE_dstPath = 'dstPath'
kPBX_PHASE_dstSubfolderSpec = 'dstSubfolderSpec'
kPBX_PHASE_shellScript = 'shellScript'
kPBX_PHASE_shellPath = 'shellPath'
kPBX_PHASE_inputPaths = 'inputPaths'
kPBX_PHASE_outputPaths = 'outputPaths'
kPBX_PHASE_showEnvVarsInLog = 'showEnvVarsInLog'

kPBX_REFERENCE_path = 'path'
kPBX_REFERENCE_name = 'name'
kPBX_REFERENCE_refType = 'refType'
kPBX_REFERENCE_sourceTree = 'sourceTree'
kPBX_REFERENCE_lastKnownFileType = 'lastKnownFileType'
kPBX_REFERENCE_fileEncoding = 'fileEncoding'
kPBX_REFERENCE_explicitFileType = 'explicitFileType'
kPBX_REFERENCE_includeInIndex = 'includeInIndex'
kPBX_REFERENCE_children = 'children'

kPBX_BUILDFILE_fileRef = 'fileRef'
kPBX_BUILDFILE_settings = 'settings'

kPBX_PROXY_remoteRef = 'remoteRef'

kPBX_PROJECT_mainGroup = 'mainGroup'
kPBX_PROJECT_targets = 'targets'
kPBX_PROJECT_attributes = 'attributes'
kPBX_PROJECT_compatibilityVersion = 'compatibilityVersion'
kPBX_PROJECT_developmentRegion = 'developmentRegion'
kPBX_PROJECT_hasScannedForEncodings = 'hasScannedForEncodings'
kPBX_PROJECT_knownRegions = 'knownRegions'
kPBX_PROJECT_productRefGroup = 'productRefGroup'
kPBX_PROJECT_projectReferences = 'projectReferences'

kPBX_PROJECTREF_ProductGroup = 'ProductGroup'
kPBX_PROJECTREF_ProjectRef = 'ProjectRef'

kPBX_TARGETDEP_target = 'target'
kPBX_TARGETDEP_targetProxy = 'targetProxy'

kPBX_CONTAINERITEMPROXY_remoteGlobalIDString = 'remoteGlobalIDString'
kPBX_CONTAINERITEMPROXY_containerPortal = 'containerPortal'

kPBX_XCBUILDCONFIG_baseConfigurationReference = 'baseConfigurationReference'

kPBX_XCCONFIGURATION_buildConfigurations = 'buildConfigurations'